/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "DAC_Output_aliases.h"
#include "DAC_Output.h"
#include "DAC_SOUND_OUT.h"
#include "BTN_DAW_aliases.h"
#include "BTN_DAW.h"
#include "BTN_LEARN_aliases.h"
#include "BTN_LEARN.h"
#include "ADC_SOUND_IN.h"
#include "LCD_Char_1.h"
#include "AMux_1.h"
#include "DAW_PITCH_aliases.h"
#include "DAW_PITCH.h"
#include "DAW_REVERB_aliases.h"
#include "DAW_REVERB.h"
#include "ADC_Input_aliases.h"
#include "ADC_Input.h"
#include "LED_GREEN_aliases.h"
#include "LED_GREEN.h"
#include "LED_YELLOW_aliases.h"
#include "LED_YELLOW.h"
#include "LED_RED_aliases.h"
#include "LED_RED.h"
#include "BTN_RECORD_aliases.h"
#include "BTN_RECORD.h"
#include "BTN_PLAY_aliases.h"
#include "BTN_PLAY.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "TFT_MOSI_aliases.h"
#include "TFT_MOSI.h"
#include "TFT_SCLK_aliases.h"
#include "TFT_SCLK.h"
#include "TFT_CS_aliases.h"
#include "TFT_CS.h"
#include "TFT_MISO_aliases.h"
#include "TFT_MISO.h"
#include "TFT_DC_aliases.h"
#include "TFT_DC.h"
#include "TFT_RESET_aliases.h"
#include "TFT_RESET.h"
#include "TFT_LED_aliases.h"
#include "TFT_LED.h"
#include "ADC_SOUND_IN_AMux.h"
#include "ADC_SOUND_IN_Ext_CP_Clk.h"
#include "ADC_SOUND_IN_IRQ.h"
#include "ADC_SOUND_IN_theACLK.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "SPIM_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

